callback: 
  development: http://192.168.1.51:3000/sessions/:sn/auth
  test: http://localhost:3000/sessions/:sn/auth

facebook:
  client_id: 158986864156387
  client_secret: d6a82d77e946d84f7844a25ec7397a1c
  authorize_url: https://graph.facebook.com/oauth/authorize
  access_token_url: https://graph.facebook.com/oauth/access_token
  profile_url: https://graph.facebook.com/me
  feed_url: https://graph.facebook.com/me/feed